# Generated by Django 5.0.1 on 2024-05-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priceM', models.IntegerField()),
                ('priceL', models.IntegerField()),
                ('pImage', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='priceL',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='priceM',
            field=models.IntegerField(),
        ),
    ]
