# Generated by Django 5.0.1 on 2024-06-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0002_burger_alter_pizza_pricel_alter_pizza_pricem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderBy', models.CharField(max_length=100)),
                ('orderDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
