# Generated by Django 5.0.1 on 2024-06-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0004_burger_category_burger_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.CharField(default='Fajita', max_length=120),
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(default='M', max_length=120),
        ),
        migrations.AlterField(
            model_name='burger',
            name='category',
            field=models.CharField(default='Zinger', max_length=120),
        ),
        migrations.AlterField(
            model_name='burger',
            name='pImage',
            field=models.URLField(default='http://example.com/default-image.jpg'),
        ),
    ]
